// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MpEntityType string

const (
	MpEntityTypeRes             MpEntityType = "res"
	MpEntityTypeWork            MpEntityType = "work"
	MpEntityTypeExpression      MpEntityType = "expression"
	MpEntityTypeManifestation   MpEntityType = "manifestation"
	MpEntityTypeItem            MpEntityType = "item"
	MpEntityTypeAgent           MpEntityType = "agent"
	MpEntityTypePerson          MpEntityType = "person"
	MpEntityTypeCollectiveAgent MpEntityType = "collective_agent"
	MpEntityTypeNomen           MpEntityType = "nomen"
	MpEntityTypePlace           MpEntityType = "place"
	MpEntityTypeTimeSpan        MpEntityType = "time_span"
	MpEntityTypeLanguage        MpEntityType = "language"
	MpEntityTypeContentRating   MpEntityType = "content_rating"
	MpEntityTypeType            MpEntityType = "type"
	MpEntityTypeStatus          MpEntityType = "status"
	MpEntityTypeTag             MpEntityType = "tag"
	MpEntityTypeDigitalResource MpEntityType = "digital_resource"
	MpEntityTypeImage           MpEntityType = "image"
	MpEntityTypeLink            MpEntityType = "link"
	MpEntityTypeRssFeed         MpEntityType = "rss_feed"
	MpEntityTypeFile            MpEntityType = "file"
)

func (e *MpEntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MpEntityType(s)
	case string:
		*e = MpEntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for MpEntityType: %T", src)
	}
	return nil
}

type NullMpEntityType struct {
	MpEntityType MpEntityType `json:"mp_entity_type"`
	Valid        bool         `json:"valid"` // Valid is true if MpEntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMpEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.MpEntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MpEntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMpEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MpEntityType), nil
}

type MpRelationshipType string

const (
	MpRelationshipTypeMPR1  MpRelationshipType = "MP_R1"
	MpRelationshipTypeMPR2  MpRelationshipType = "MP_R2"
	MpRelationshipTypeMPR3  MpRelationshipType = "MP_R3"
	MpRelationshipTypeMPR4  MpRelationshipType = "MP_R4"
	MpRelationshipTypeMPR5  MpRelationshipType = "MP_R5"
	MpRelationshipTypeMPR6  MpRelationshipType = "MP_R6"
	MpRelationshipTypeMPR7  MpRelationshipType = "MP_R7"
	MpRelationshipTypeMPR8  MpRelationshipType = "MP_R8"
	MpRelationshipTypeMPR9  MpRelationshipType = "MP_R9"
	MpRelationshipTypeMPR10 MpRelationshipType = "MP_R10"
	MpRelationshipTypeMPR11 MpRelationshipType = "MP_R11"
	MpRelationshipTypeMPR12 MpRelationshipType = "MP_R12"
	MpRelationshipTypeMPR13 MpRelationshipType = "MP_R13"
	MpRelationshipTypeMPR14 MpRelationshipType = "MP_R14"
	MpRelationshipTypeMPR15 MpRelationshipType = "MP_R15"
	MpRelationshipTypeMPR16 MpRelationshipType = "MP_R16"
	MpRelationshipTypeMPR17 MpRelationshipType = "MP_R17"
	MpRelationshipTypeMPR18 MpRelationshipType = "MP_R18"
	MpRelationshipTypeMPR19 MpRelationshipType = "MP_R19"
	MpRelationshipTypeMPR20 MpRelationshipType = "MP_R20"
	MpRelationshipTypeMPR21 MpRelationshipType = "MP_R21"
	MpRelationshipTypeMPR22 MpRelationshipType = "MP_R22"
	MpRelationshipTypeMPR23 MpRelationshipType = "MP_R23"
	MpRelationshipTypeMPR24 MpRelationshipType = "MP_R24"
	MpRelationshipTypeMPR25 MpRelationshipType = "MP_R25"
	MpRelationshipTypeMPR26 MpRelationshipType = "MP_R26"
	MpRelationshipTypeMPR27 MpRelationshipType = "MP_R27"
	MpRelationshipTypeMPR28 MpRelationshipType = "MP_R28"
	MpRelationshipTypeMPR29 MpRelationshipType = "MP_R29"
	MpRelationshipTypeMPR30 MpRelationshipType = "MP_R30"
	MpRelationshipTypeMPR31 MpRelationshipType = "MP_R31"
	MpRelationshipTypeMPR32 MpRelationshipType = "MP_R32"
	MpRelationshipTypeMPR33 MpRelationshipType = "MP_R33"
	MpRelationshipTypeMPR34 MpRelationshipType = "MP_R34"
	MpRelationshipTypeMPR35 MpRelationshipType = "MP_R35"
	MpRelationshipTypeMPR36 MpRelationshipType = "MP_R36"
	MpRelationshipTypeMPR37 MpRelationshipType = "MP_R37"
	MpRelationshipTypeMPR38 MpRelationshipType = "MP_R38"
	MpRelationshipTypeMPR39 MpRelationshipType = "MP_R39"
	MpRelationshipTypeMPR40 MpRelationshipType = "MP_R40"
)

func (e *MpRelationshipType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MpRelationshipType(s)
	case string:
		*e = MpRelationshipType(s)
	default:
		return fmt.Errorf("unsupported scan type for MpRelationshipType: %T", src)
	}
	return nil
}

type NullMpRelationshipType struct {
	MpRelationshipType MpRelationshipType `json:"mp_relationship_type"`
	Valid              bool               `json:"valid"` // Valid is true if MpRelationshipType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMpRelationshipType) Scan(value interface{}) error {
	if value == nil {
		ns.MpRelationshipType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MpRelationshipType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMpRelationshipType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MpRelationshipType), nil
}

// MP-E6 (LRM-E6): Superclass for Person and Collective Agent.
type MpAgent struct {
	ID              pgtype.UUID `json:"id"`
	ContactInfo     []string    `json:"contact_info"`
	FieldOfActivity []string    `json:"field_of_activity"`
	Language        []string    `json:"language"`
}

// MP-E8 (LRM-E8): A gathering or organization acting as a unit.
type MpCollectiveAgent struct {
	ID               pgtype.UUID `json:"id"`
	OrganizationType pgtype.Text `json:"organization_type"`
}

// Custom entity for content advisories.
type MpContentRating struct {
	ID pgtype.UUID `json:"id"`
	// e.g. MPAA, ESRB
	Authority   pgtype.Text `json:"authority"`
	RatingValue pgtype.Text `json:"rating_value"`
}

// Custom superclass for digital assets.
type MpDigitalResource struct {
	ID                 pgtype.UUID `json:"id"`
	Uri                pgtype.Text `json:"uri"`
	AccessRestrictions []string    `json:"access_restrictions"`
}

// MP-E3 (LRM-E3): A distinct combination of signs conveying content.
type MpExpression struct {
	ID pgtype.UUID `json:"id"`
	// e.g. content type, notation
	Category []string `json:"category"`
	// e.g. duration, word count
	Extent            []string `json:"extent"`
	IntendedAudience  []string `json:"intended_audience"`
	UseRights         []string `json:"use_rights"`
	CartographicScale []string `json:"cartographic_scale"`
	// LRM-E3-A6
	Language []string `json:"language"`
	// LRM-E3-A7
	MusicalKey []string `json:"musical_key"`
	// LRM-E3-A8
	MediumOfPerformance []string `json:"medium_of_performance"`
}

type MpFile struct {
	ID            pgtype.UUID `json:"id"`
	Filename      pgtype.Text `json:"filename"`
	FileSizeBytes pgtype.Int8 `json:"file_size_bytes"`
	Checksum      pgtype.Text `json:"checksum"`
	Extension     pgtype.Text `json:"extension"`
}

type MpImage struct {
	ID       pgtype.UUID `json:"id"`
	Width    pgtype.Int4 `json:"width"`
	Height   pgtype.Int4 `json:"height"`
	MimeType pgtype.Text `json:"mime_type"`
}

// MP-E5 (LRM-E5): An object carrying signs (The concrete copy).
type MpItem struct {
	ID pgtype.UUID `json:"id"`
	// Shelf mark, repository
	Location []string `json:"location"`
	// Specific to this copy
	UseRights []string `json:"use_rights"`
}

// Custom entity for managing language controlled vocabulary.
type MpLanguage struct {
	ID      pgtype.UUID `json:"id"`
	IsoCode pgtype.Text `json:"iso_code"`
	Name    pgtype.Text `json:"name"`
}

type MpLink struct {
	ID          pgtype.UUID        `json:"id"`
	TargetUrl   pgtype.Text        `json:"target_url"`
	LastChecked pgtype.Timestamptz `json:"last_checked"`
}

// MP-E4 (LRM-E4): A set of all carriers sharing the same content/form.
type MpManifestation struct {
	ID pgtype.UUID `json:"id"`
	// e.g. volume, online resource
	CarrierCategory  []string `json:"carrier_category"`
	Extent           []string `json:"extent"`
	IntendedAudience []string `json:"intended_audience"`
	// Transcribed title, imprint, etc.
	ManifestationStatement []string `json:"manifestation_statement"`
	AccessConditions       []string `json:"access_conditions"`
	UseRights              []string `json:"use_rights"`
}

// MP-E9 (LRM-E9): An association between an entity and a designation.
type MpNoman struct {
	ID pgtype.UUID `json:"id"`
	// e.g. identifier, name, title
	Category    []string `json:"category"`
	NomenString string   `json:"nomen_string"`
	// e.g. ISBN, LCSH
	Scheme           []string `json:"scheme"`
	IntendedAudience []string `json:"intended_audience"`
	ContextOfUse     []string `json:"context_of_use"`
	ReferenceSource  []string `json:"reference_source"`
	Language         []string `json:"language"`
	Script           []string `json:"script"`
	ScriptConversion []string `json:"script_conversion"`
}

// MP-E7 (LRM-E7): An individual human being.
type MpPerson struct {
	ID         pgtype.UUID `json:"id"`
	Profession []string    `json:"profession"`
}

// MP-E10 (LRM-E10): A given extent of space.
type MpPlace struct {
	ID       pgtype.UUID `json:"id"`
	Category []string    `json:"category"`
	// GeoJSON or coordinates
	LocationData []byte `json:"location_data"`
}

// MP-E1 (LRM-E1): Top level entity. All other entities inherit from this via 1:1 FK.
type MpRe struct {
	ID pgtype.UUID `json:"id"`
	// Discriminator for Class Table Inheritance
	EntityType MpEntityType `json:"entity_type"`
	// Multivalued attribute
	Note      []string           `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Generic link table implementing the Unified MP Relationship Model. Connects any Res to any Res based on the definition in mp_relationship_type.
type MpRelationship struct {
	ID        pgtype.UUID        `json:"id"`
	SourceID  pgtype.UUID        `json:"source_id"`
	TargetID  pgtype.UUID        `json:"target_id"`
	RelType   MpRelationshipType `json:"rel_type"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	Note      pgtype.Text        `json:"note"`
}

type MpRssFeed struct {
	ID              pgtype.UUID `json:"id"`
	FeedUrl         pgtype.Text `json:"feed_url"`
	UpdateFrequency pgtype.Text `json:"update_frequency"`
}

// Custom entity for workflow status.
type MpStatus struct {
	ID         pgtype.UUID `json:"id"`
	StatusCode pgtype.Text `json:"status_code"`
	Label      pgtype.Text `json:"label"`
}

// Custom entity for folksonomy/tagging.
type MpTag struct {
	ID    pgtype.UUID `json:"id"`
	Label pgtype.Text `json:"label"`
	Slug  pgtype.Text `json:"slug"`
}

// MP-E11 (LRM-E11): A temporal extent.
type MpTimeSpan struct {
	ID        pgtype.UUID        `json:"id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	Duration  pgtype.Interval    `json:"duration"`
}

// Custom entity for resource typing.
type MpType struct {
	ID       pgtype.UUID `json:"id"`
	Category pgtype.Text `json:"category"`
	Label    pgtype.Text `json:"label"`
}

// MP-E2 (LRM-E2): The intellectual or artistic content.
type MpWork struct {
	ID pgtype.UUID `json:"id"`
	// e.g. termination intention, creative domain
	Category []string `json:"category"`
	// Stores cached values from the canonical expression (Key, Language, Scale)
	RepresentativeAttributes []byte `json:"representative_attributes"`
}
