// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAgent(ctx context.Context, arg CreateAgentParams) error
	CreatePerson(ctx context.Context, arg CreatePersonParams) error
	CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (pgtype.UUID, error)
	CreateRes(ctx context.Context, arg CreateResParams) (CreateResRow, error)
	CreateWork(ctx context.Context, arg CreateWorkParams) error
	// Returns a fully hydrated Person by joining the inheritance tables
	GetPerson(ctx context.Context, id pgtype.UUID) (GetPersonRow, error)
	GetWork(ctx context.Context, id pgtype.UUID) (GetWorkRow, error)
	// Demonstrates graph traversal: Find all works created by a specific person
	GetWorksByCreator(ctx context.Context, targetID pgtype.UUID) ([]GetWorksByCreatorRow, error)
}

var _ Querier = (*Queries)(nil)
